plugins {
    id 'com.android.application'
}

android {
    namespace = 'com.ncy'
    compileSdk = 34

    defaultConfig {
        applicationId = "com.ncy"
        minSdk = 29
        targetSdk = 34
        versionCode = 2
        versionName = "1.0.0"
    }

    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
            signingConfig signingConfigs.debug
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
}

dependencies {
    // Tu proyecto es tan nativo y limpio que no necesitas librerías externas por ahora.
}